cavapoos/config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root 'home#index'

  resources :puppies
  resources :home
end

cavapoos/app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

cavapoos/app/models/puppy.rb
class Puppy < ActiveRecord::Base
end

cavapoos/app/controllers/admin/confirmations_controller.rb
class Admin::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

cavapoos/app/controllers/admin/omniauth_callbacks_controller.rb
class Admin::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

cavapoos/app/controllers/admin/passwords_controller.rb
class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

cavapoos/app/controllers/admin/registrations_controller.rb
class Admin::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

cavapoos/app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    redirect_to '/'
  end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

cavapoos/app/controllers/admin/unlocks_controller.rb
class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

cavapoos/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

cavapoos/app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    @puppies = Puppy.all
  end

  def new
    @puppy = Puppy.new
  end

  def create
    @puppy = Puppy.create(puppy_params)
    if @puppy.save
      redirect_to '/admin'
    else
      render :new
    end
  end

  def edit
    @puppy = Puppy.find(params[:id])
  end

  def update
  end

  def destroy
  end

  private

  def puppy_params
    params.require(:puppy).permit(:pic, :description, :price)
  end

end

cavapoos/app/controllers/puppies_controller.rb
class PuppiesController < ApplicationController
end

cavapoos/app/helpers/admin_helper.rb
module AdminHelper
end

cavapoos/app/helpers/application_helper.rb
module ApplicationHelper
end

cavapoos/app/helpers/home_helper.rb
module HomeHelper
end

cavapoos/app/helpers/puppies_helper.rb
module PuppiesHelper
end

cavapoos/app/views/home/index.html.erb
  <div class="row">
    <div class="col s12 teal lighten-4 z-depth-1">
      <div class="row">
        <div class="col s6 left">
          <img class="responsive-image p2_image" src="<%= image_path("cavapoo.jpg") %>">
        </div>
        <div class="col s6 right">
          <h3 class="center">About Cavapoochons</h3>
          <hr/>
          <p>
            The Cavapoochon is a tribrid and mixes the three popular breeds of the Cavalier King Charles Spaniel,
            Toy Poodle and Bichon Frise. The Cavapoochon is a new breed that has recently started being bred in the USA.
            They have been hailed as the dog that ‘never loses its puppy face’.we are the first liscenced kennel to breed these beautiful pups in
            ireland. The cavapoochon is a small playful dog full of character and is hypoallergenic so they are perfect for allergy sufferers.
          </p>
        </div>
      </div>
    </div>
     <% if @puppies.any? %>
      <div class="col s8 offset-s2 pup_div">
        <% if admin_signed_in? %>
          <% @puppies.each do |puppy| %>
              <img class="responsive-image circle p_image " src="<%= image_path("cavapoo.jpg") %>">
              <p class="center"><%= "$#{puppy.price}" %></p>
              <hr/>
          <% end %>
        <% else %>
          <% @puppies.each do |puppy| %>
            <img class="responsive-image circle p_image " src="<%= image_path("cavapoo.jpg") %>">
            <p class="center"><%= "$#{puppy.price}" %></p>
            <hr/>
          <% end %>
        <% end %>
    <% else %>
      h3>There are currently no puppies!</h3>
    </div>
    <% end %>
  </div>

cavapoos/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cavapoos</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--Import Google Icon Font-->
  <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <!--Import materialize.css-->
  <link type="text/css" rel="stylesheet" href="css/materialize.min.css"  media="screen,projection"/>
  <!--Let browser know website is optimized for mobile-->
 <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>
<body>
  <% if admin_signed_in? %>
    <div class="navbar-fixed">
      <nav class="white bar">
        <div class="nav-wrapper">
          <img href="/" class="brand-logo center logo" src="<%= image_path("cavapoos-logo5.png") %>"></img>
          <ul id="nav-mobile" class="right">
            <li><a class="teal-text text-accent-2"><%= link_to 'Logout', destroy_admin_session_path , method: :delete %></a></li>
            <li><a href="#" class="teal-text text-accent-2">New Puppy</a></li>
          </ul>
        </div>
      </nav>
    </div>
  <% else %>
    <div class="navbar-fixed">
      <nav class="white bar">
        <div class="nav-wrapper">
          <img href="/" class="brand-logo center logo" src="<%= image_path("cavapoos-logo5.png") %>"></img>
          <ul id="nav-mobile" class="right">
            <li><a href="" class="black-text">Email</a></li>
            <li><a href="" class="black-text">Facebook</a></li>
          </ul>
        </div>
      </nav>
    </div>
  <% end %>

  <div class="hide">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </div>

<%= yield %>
</body>
</html>